# Generated by Django 6.0 on 2026-02-14 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlbumManager', '0002_artista_remove_album_genero_alter_album_artista_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='num_canciones',
        ),
        migrations.AddField(
            model_name='artista',
            name='pais',
            field=models.CharField(default='España', max_length=50),
        ),
        migrations.AlterField(
            model_name='album',
            name='artista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AlbumManager.artista'),
        ),
        migrations.AlterField(
            model_name='cancion',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AlbumManager.album'),
        ),
        migrations.AlterField(
            model_name='cancion',
            name='duracion',
            field=models.IntegerField(help_text='Duración en segundos'),
        ),
    ]
